version: '3'
services:
  db:
    build:
      dockerfile: Dockerfile-db
      context: './docker'
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 54325:5432
    environment:
      POSTGRES_DB: shagaan_backend

  node-app:
    build: .
    ports: 
      - "8080:8080"